function y = FiltrCheb(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 08-Oct-2021 21:36:03

persistent Hd;

if isempty(Hd)
    
    Fstop = 0.4;   % Stopband Frequency
    Fpass = 0.8;   % Passband Frequency
    Astop = 40;   % Stopband Attenuation (dB)
    Apass = 0.9;    % Passband Ripple (dB)
    Fs    = 100;  % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'equiripple', 'MinOrder', 'any',  'StopbandShape', 'flat');
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

