function y = FNChEleps(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 15-Oct-2021 08:49:51

persistent Hd;

if isempty(Hd)
    
    Fstop = 0.4;  % Stopband Frequency
    Fpass = 0.8;  % Passband Frequency
    Astop = 40;   % Stopband Attenuation (dB)
    Apass = 0.9;  % Passband Ripple (dB)
    Fs    = 100;  % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'ellip', ...
        'MatchExactly', 'both', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

